# Generated by Django 6.0.3 on 2026-05-23 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_studentprofile'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('student', 'job')},
        ),
        migrations.AddField(
            model_name='application',
            name='drivestatus',
            field=models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='requested', max_length=20),
        ),
        migrations.AddField(
            model_name='application',
            name='roundstatus',
            field=models.CharField(choices=[('none', 'None'), ('shortlisted', 'Shortlisted'), ('eliminated', 'Eliminated'), ('selected', 'Selected')], default='none', max_length=20),
        ),
        migrations.RemoveField(
            model_name='application',
            name='status',
        ),
    ]
